### ISSUE TITLE
Tempest reading for Lightning Strike Count always at 0

### ISSUE THREAD

**Issue by beaulebens** [briis/pysmartweather#9]
I'm observing a lighting storm right now, and my Tempest device is registering over 100 lightning strikes. I happened to check my HA integration using this library, and it's showing "0" strikes, so I assume the value is not being passed through correctly.

From a quick look I don't see why -- `lightning_count` seems to be handled, but it's definitely not making it through to HA correctly.

<img width="971" alt="Screen Shot 2020-07-09 at 8 33 21 PM" src="https://user-images.githubusercontent.com/108942/87110096-74f3cc80-c223-11ea-82b7-2c7bf81adaca.png">

**Comment by LuckyJayDIY** [comment]
That seems to be an issue with the Tempest firmware.  I noted the same thing and opened a support ticket with WeatherFlow and received this response:

**Thanks for writing in. This is a known bug in Tempest's firmware and our team expects to have a new Tempest firmware candidate ready for testing after we have finished upgrading the network with the latest Hub firmware (v143).

Thanks for bringing this to our attention and we appreciate your support!
Kind Regards, 
William Gidley
WeatherFlow Support**
